version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
       - AUTH=yes
       - MONGODB_ADMIN_USER=root
       - MONGODB_ADMIN_PASS=example
       - MONGODB_APPLICATION_DATABASE=test,order
       - MONGODB_APPLICATION_USER=app
       - MONGODB_APPLICATION_PASS=1qaz2wsx
#
#
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#       - MONGODB_APPLICATION_DATABASE=sample
#            - MONGODB_APPLICATION_USER=aashrey
#            - MONGODB_APPLICATION_PASS=admin123
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
      - ./mongoconfig:/data/configdb

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example